name: maintenance_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <=4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dropdown_button2: ^1.6.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.2.1
  flutter_native_splash: ^2.1.5
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  google_fonts: ^6.1.0
  json_annotation: ^4.5.0
  qr_code_scanner: ^1.0.0
  salomon_bottom_bar: ^3.3.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#1868B2"
  image: assets/images/logo.png
  android: true
  ios: true
